name: Update README Version

on:
  release:
    types: [published]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get release version
        id: version
        run: |
          echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          echo "version_no_v=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update version in files
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          VERSION_NO_V="${VERSION#v}"
          
          # Update package.json version
          sed -i "s|\"version\": \"[0-9]*\.[0-9]*\.[0-9]*\"|\"version\": \"${VERSION_NO_V}\"|g" package.json
          
          # Update quick install command in README
          sed -i "s|https://github.com/phyter1/tts-cli/releases/download/v[0-9]*\.[0-9]*\.[0-9]*/install.sh|https://github.com/phyter1/tts-cli/releases/download/${VERSION}/install.sh|g" README.md
          
          # Update download table links in README
          sed -i "s|https://github.com/phyter1/tts-cli/releases/download/v[0-9]*\.[0-9]*\.[0-9]*/tts-cli-|https://github.com/phyter1/tts-cli/releases/download/${VERSION}/tts-cli-|g" README.md
          
          # Update manual install example in README
          sed -i "s|curl -L https://github.com/phyter1/tts-cli/releases/download/v[0-9]*\.[0-9]*\.[0-9]*/|curl -L https://github.com/phyter1/tts-cli/releases/download/${VERSION}/|g" README.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update version to ${{ steps.version.outputs.version }}"
          title: "chore: update version for release ${{ steps.version.outputs.version }}"
          body: |
            This PR automatically updates the version in project files for the latest release.
            
            Changes:
            - Updated package.json version to ${{ steps.version.outputs.version }}
            - Updated README quick install script URL to ${{ steps.version.outputs.version }}
            - Updated README download table links to ${{ steps.version.outputs.version }}
            - Updated README manual installation examples to ${{ steps.version.outputs.version }}
            
            This is an automated PR generated by the release workflow.
          branch: update-readme-${{ steps.version.outputs.version }}
          delete-branch: true
          labels: documentation, automated